##
# Deployment of the Islandora Bagger container
#
##

secrets:
  BAGGER_DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: ./custom/secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD

volumes:
  bagger-data: {}
  bagger-aip: {}

# Common to all services
x-common: &common
  restart: "no"

# Common build settings
x-build-common: &build-common
  args:
    REPOSITORY: ${ISLE_REPOSITORY:-docker.io/islandora}
    TAG: ${ISLE_TAG:-latest}
  x-bake:
    platforms:
      - linux/amd64
        #- linux/arm64

services:

  bagger:
    <<: *common
    build:
      <<: *build-common
      #context: ./bagger/
      context: .
    environment:
      BAGGER_DRUPAL_URL: ${SITE:-"https://islandora.dev"}
      BAGGER_CROND_ENABLE_SERVICE: ${BAGGER_CROND_ENABLE_SERVICE:-"true"}
      BAGGER_CROND_SCHEDULE: ${BAGGER_CROND_SCHEDULE:-1 2 * * *}
      BAGGER_CROND_LOG_LEVEL: ${BAGGER_CROND_LOG_LEVEL:-"8"}
      BAGGER_OUTPUT_DIR: ${BAGGER_OUTPUT_DIR:-"/data/aip/"}
      BAGGER_BAG_DOWNLOAD_PREFIX: ${BAGGER_BAG_DOWNLOAD_PREFIX:-""}  # unused
      BAGGER_DEFAULT_PER_BAG_NAME_TEMPLATE: ${BAGGER_DEFAULT_PER_BAG_NAME_TEMPLATE:-"aip_%"}
      BAGGER_DEFAULT_PER_BAG_CONTACT_NAME: ${BAGGER_DEFAULT_PER_BAG_CONTACT_NAME:-Contact Name}
      BAGGER_DEFAULT_PER_BAG_CONTACT_EMAIL: ${BAGGER_DEFAULT_PER_BAG_CONTACT_EMAIL:-Contact EMail}
      BAGGER_DEFAULT_PER_BAG_SOURCE_ORGANIZATION: ${BAGGER_DEFAULT_PER_BAG_SOURCE_ORGANIZATION:-Contact Organization}
      BAGGER_DEFAULT_PER_BAG_HTTP_TIMEOUT: ${BAGGER_DEFAULT_PER_BAG_HTTP_TIMEOUT:-"120"}
      BAGGER_DEFAULT_PER_BAG_DELETE_SETTINGS_FILE: ${BAGGER_DEFAULT_PER_BAG_DELETE_SETTINGS_FILE:-"false"}
      BAGGER_DEFAULT_PER_BAG_LOG_BAG_CREATION: ${BAGGER_DEFAULT_PER_BAG_LOG_BAG_CREATION:-"true"}
      BAGGER_DEFAULT_PER_BAG_LOG_BAG_LOCATION: ${BAGGER_DEFAULT_PER_BAG_LOG_BAG_LOCATION:-"false"}
      BAGGER_DEFAULT_PER_BAG_REGISTER_BAGS_WITH_ISLANDORA: ${BAGGER_DEFAULT_PER_BAG_REGISTER_BAGS_WITH_ISLANDORA:-"false"}
    image: ${BAGGER_REPOSITORY}/isle-bagger:${BAGGER_TAG}
    ports:
      - 9856:8000
    secrets:
    #   - source: UID
    #   - source: GID
      - source: BAGGER_DRUPAL_DEFAULT_ACCOUNT_PASSWORD
    volumes:
      - bagger-data:/var/www/bagger/var
      - bagger-aip:${BAGGER_OUTPUT_DIR:-/data/aip}
