# Deployment of the Islandora Bagger container alongside an isle-site-template
#
# Steps:
#   * add the following to the `.env` file
#     # Chain docker-compose.yml files
#     COMPOSE_PATH_SEPARATOR=:
#     COMPOSE_FILE=docker-compose.yml:docker-compose.bagger.yml
#     # Environment for the Islandora Bagger container
#     BAGGER_REPOSITORY=cwrc
#     BAGGER_TAG=latest
#     BAGGER_DEFAULT_PER_BAG_REGISTER_BAGS_WITH_ISLANDORA=true
#
#   * copy this file into the repo
#   * temporarily for a dev site, copy local `build/certs/rootCA.pem` into the container /etc/ssl/certs/ca-certificates.crt otherwise REST request receive a cert error (e.g., curl)

x-dev: &dev
  secrets:
    - source: CERT_PUBLIC_KEY
    - source: CERT_PRIVATE_KEY
    - source: CERT_AUTHORITY
    - source: UID
    - source: GID
    - source: BAGGER_DRUPAL_DEFAULT_ACCOUNT_PASSWORD

x-devs: &devs
    - source: CERT_PUBLIC_KEY

secrets:
  UID:
    file: ./custom/secrets/UID
  GID:
    file: ./custom/secrets/UID
  BAGGER_DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: ./custom/secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD
  # Certificates are only used for development environments.
  # In production the expectation is to use lets encrypt, etc.
  # See README.md for how to generate them.
  CERT_PUBLIC_KEY:
    file: ./build/certs/cert.pem
  CERT_PRIVATE_KEY:
    file: ./build/certs/privkey.pem
  CERT_AUTHORITY:
    file: ./build/certs/rootCA.pem

volumes:
  bagger-data: {}

services:

  bagger:
    <<: *dev
    restart: "no"
    environment:
      BAGGER_DRUPAL_URL: ${SITE:-"https://islandora.dev"} 
      BAGGER_CROND_ENABLE_SERVICE: ${BAGGER_CROND_ENABLE_SERVICE:-"true"}
      BAGGER_CROND_SCHEDULE: ${BAGGER_CROND_SCHEDULE:-1 2 * * *}
      BAGGER_CROND_LOG_LEVEL: ${BAGGER_CROND_LOG_LEVEL:-"8"}
      BAGGER_BAG_DOWNLOAD_PREFIX: ${BAGGER_BAG_DOWNLOAD_PREFIX:-""}  # unused
      BAGGER_DEFAULT_PER_BAG_NAME_TEMPLATE: ${BAGGER_DEFAULT_PER_BAG_NAME_TEMPLATE:-"aip_%"}
      BAGGER_DEFAULT_PER_BAG_CONTACT_NAME: ${BAGGER_DEFAULT_PER_BAG_CONTACT_NAME:-Contact Name}
      BAGGER_DEFAULT_PER_BAG_CONTACT_EMAIL: ${BAGGER_DEFAULT_PER_BAG_CONTACT_EMAIL:-Contact EMail}
      BAGGER_DEFAULT_PER_BAG_SOURCE_ORGANIZATION: ${BAGGER_DEFAULT_PER_BAG_SOURCE_ORGANIZATION:-Contact Organization}
      BAGGER_DEFAULT_PER_BAG_HTTP_TIMEOUT: ${BAGGER_DEFAULT_PER_BAG_HTTP_TIMEOUT:-"120"}
      BAGGER_DEFAULT_PER_BAG_DELETE_SETTINGS_FILE: ${BAGGER_DEFAULT_PER_BAG_DELETE_SETTINGS_FILE:-"false"}
      BAGGER_DEFAULT_PER_BAG_LOG_BAG_CREATION: ${BAGGER_DEFAULT_PER_BAG_LOG_BAG_CREATION:-"true"}
      BAGGER_DEFAULT_PER_BAG_LOG_BAG_LOCATION: ${BAGGER_DEFAULT_PER_BAG_LOG_BAG_LOCATION:-"false"}
      BAGGER_DEFAULT_PER_BAG_REGISTER_BAGS_WITH_ISLANDORA: ${BAGGER_DEFAULT_PER_BAG_REGISTER_BAGS_WITH_ISLANDORA:-"false"}
    image: ${BAGGER_REPOSITORY}/isle-bagger:${BAGGER_TAG}
    networks:
      default: {}
    ports: 
      - 9856:8000
    volumes:
      - bagger-data:/var/www/bagger/var
