#!/command/with-contenv bash
# shellcheck shell=bash
set -e

# Only run the service if explicitly told to do so.
if [[ "${BAGGER_CROND_ENABLE_SERVICE}" == "true" ]]; then
  exec crond -f -l "${BAGGER_CROND_LOG_LEVEL}" -d "${BAGGER_CROND_LOG_LEVEL}"
fi
